### ISSUE TITLE
How to get Buffered HRV 

### ISSUE THREAD

**Issue by devhci** [movisens/MovisensGattLib#3]
Hi,

I am using EcgMove__4_0_1__default device. I have a question regarding getting buffer HRV  over Bluetooth.

I am able to retrieve Buffered HR_mean with below code 
`private  void splitAndSaveHR(HrMeanBuffered  hrMeanBuffered){

        String[] splits = hrMeanBuffered.toString().split("[\\r\\n]+");

        for (int i = 0; i < splits.length; i++) {

            DateTime timestamp = new DateTime((hrMeanBuffered.getTime().getTime() / 1000 + (long) (1 / hrMeanBuffered.getSamplerate() * i)) * 1000);
            int hr = hrMeanBuffered.getHrMean()[i];

            log("UpdateSensorData", "Time: " + TimeFormatUtil.getStringFromDate(timestamp) + " " + "HR: " + hrMeanBuffered.getHrMean()[i]);
        }

    }`
 

But In the case of buffered HRV

There is hrvIsValidBuffered.getHrvIsValid()[i]  which is a   Boolen[] .....   How can I get the   numeric BufferedHRV  value ?

Thanks!

**Comment by jottenbacher** [comment]
Buffered HRV data (HRV parameter RMSSD) is in RmssdBuffered
HrvIsValidBuffered tells if the ECG signal is good enough for HRV calculation

**Comment by devhci** [comment]
Thanks @jottenbacher .  I am able to retrieve it now.

I have one more question, I don't know if I should ask it in this thread. Is TapMarkerBuffered supported in EcgMove__4_0_1__default ?  I know that on the documentation page https://www.movisens.com/en/ble-specification/  it only shows TapMarker and not TapMarkerBuffered.  Also, the current version of MovisensGittLib does not have TapMarkerBuffered. However, I have an old version of MovisensGittLib(~2.1.4) which contains  TapMarkerBuffered class. Just wanna confirm if TapMarkerBuffered is no longer supported in EcgMove__4_0_1__default  or other device versions 

In our application, we need TapMarkerBuffer instead of TapMarker as we can't afford to miss any tapMarker data in case of disconnection.
